### ISSUE TITLE
preact instead of react

### ISSUE THREAD

**Issue by 3nt3** [BixConcept/tutoring-frontend#33]
[Preact](https://preactjs.com/) is a "Fast 3kB alternative to React with the same modern API" which is considerably more performant [in benchmarks](https://developit.github.io/preact-perf/)

Should we maybe try to integrate preact instead of react since most of the features we use are pretty limited and probably will work with preact

@LaurensHei @soysalayberk @sanberksoysal

**Comment by LaurensHei** [comment]
nein.


das können wir höltgen nicht antun. und unsere webseite ist schnell genug

**Comment by 3nt3** [comment]
@LaurensHei  unsere website is >200K groß und das ist mmn viel zu groß. Preact is mit react kompatibel also sollte herr höltgen ok damit sein

**Comment by LaurensHei** [comment]
wie lange braucht die seite zum laden?

**Comment by 3nt3** [comment]
> wie lange braucht die seite zum laden?

bei mir ohne cache etwa 2 sekunden

**Comment by 3nt3** [comment]
> also ka für mich schreit das irgendwie nach unnötigen problemen die aufkommen

also nach meinem jetzigen wissensstand sollte das für uns keine probleme geben, und wenn doch können wirs ja auch mit minimalem aufwand wieder rausnehmen.

**Comment by 3nt3** [comment]
Hier mal zum Vergleich unsere Lighthouse scores:

Ich denke mal wir sollten schon versuchen, die Zahlen *deutlich* besser zu machen, vor allem auf mobile, wo (ich spekuliere mal aber ich denke dabie sind wir uns eigentlich einig) unsere meisten user wären.

### auf mobile
![Screenshot 2022-02-05 231807](https://user-images.githubusercontent.com/39235738/152660833-0cb33ddb-76b3-487c-b537-5b88b04b5c63.png)


### auf desktop
![Screenshot 2022-02-05 231741](https://user-images.githubusercontent.com/39235738/152660845-e88811df-3a75-456c-82dc-f8a1848920d0.png)

**Comment by 3nt3** [comment]
> wie lange braucht die seite zum laden?

7 Sekunden mit 3g glaub ich
